-- 공지사항 테이블
CREATE TABLE TB_NOTICE (
    N_IDX      INTEGER PRIMARY KEY NOT NULL,
    N_CATEGORY VARCHAR(30) NOT NULL,
    N_TITLE    VARCHAR(50) NOT NULL,
    N_CONTENT  VARCHAR(2000) NOT NULL,
    N_REGDATE  DATE DEFAULT SYSDATE,
    N_UPDATE   DATE DEFAULT SYSDATE,
    N_STATUS   CHAR(1) DEFAULT 'N'
);

-- 공지사항 번호 자동증가용 시퀀스
CREATE SEQUENCE N_IDX
    START WITH 1
    INCREMENT BY 1;



-- 출력용 더미 데이터 삽입
INSERT INTO TB_NOTICE (N_IDX, N_CATEGORY, N_TITLE, N_CONTENT, N_REGDATE, N_UPDATE, N_STATUS)
VALUES (N_IDX.NEXTVAL, '일반', '첫 번째 일반 공지', '첫 번째 공지 내용입니다.', SYSDATE, SYSDATE, 'Y');

INSERT INTO TB_NOTICE (N_IDX, N_CATEGORY, N_TITLE, N_CONTENT, N_REGDATE, N_UPDATE, N_STATUS)
VALUES (N_IDX.NEXTVAL, '오픈소식', '두 번째 오픈소식 공지', '두 번째 공지 내용입니다.', SYSDATE, SYSDATE, 'Y');

INSERT INTO TB_NOTICE (N_IDX, N_CATEGORY, N_TITLE, N_CONTENT, N_REGDATE, N_UPDATE, N_STATUS)
VALUES (N_IDX.NEXTVAL, '서비스', '세 번째 서비스 공지', '세 번째 공지 내용입니다.', SYSDATE, SYSDATE, 'N');

INSERT INTO TB_NOTICE (N_IDX, N_CATEGORY, N_TITLE, N_CONTENT, N_REGDATE, N_UPDATE, N_STATUS)
VALUES (N_IDX.NEXTVAL, '당첨자 발표', '네 번째 당첨자 발표 공지', '네 번째 공지 내용입니다.', SYSDATE, SYSDATE, 'Y');

INSERT INTO TB_NOTICE (N_IDX, N_CATEGORY, N_TITLE, N_CONTENT, N_REGDATE, N_UPDATE, N_STATUS)
VALUES (N_IDX.NEXTVAL, '일반', '다섯 번째 일반 공지', '다섯 번째 공지 내용입니다.', SYSDATE, SYSDATE, 'N');